
name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify your PHP version
          extensions: mbstring, xml, zip, gd, mysqli  # Add any required extensions

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel migrations
        run: php artisan migrate --force

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.betteredgestechnologies.com.ng
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          clean: true 
