on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploying

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Directory Permissions
      run: chmod -R 775 storage

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.betteredgestechnologies.com.ng 
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}