
name: Deploy to FTP

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' 
        
      - name: Remove cached bootstrap file
        run: sudo rm -rf bootstrap/services.php bootstrap/cache/packages.php
        
      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.betteredgestechnologies.com.ng
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
